#!/usr/bin/env bash

set -e;

case "$1" in
  
  sinopia)
    echo "info"
    ;;
    
  sinopia:expose)
    echo "expose"
    ;;
  
  sinopia:hide)
    echo "hide"
    ;;
    
  sinopia:backup)
    echo "backup"
    ;;
    
  sinopia:reconfig)
    echo "reconfig"
    ;;
    
  sinopia:remove)
    
    ;;

  help)
    cat && cat<<EOF
    sinopia                     Get infos about the private sinopia registry
    sinopia:expose              Binds the sinopia container to a higher port on host (restarts sinopia)
    sinopia:hide                Unbinds the sinopia container from a port on host (restarts sinopia)
    sinopia:backup              Backups the sinopia storage folder
    sinopia:reconfig            Updates the sinopia config (restarts sinopia)
    sinopia:remove              Deletes the sinopia containers and the sinopia folder on dokku host
EOF
    ;;

esac
